databases:
  - name: woh
    plan: free
    databaseName: woh
    user: woh

services:
  - type: web
    plan: free
    name: woh
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn woh.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: woh
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4